// eslint-disable-next-line import/no-anonymous-default-export
export default {
  PRODUCTS_FILTER_PRICE: "PRODUCTS_FILTER_PRICE",
  PRODUCTS_SORT_EXPENSIVE: "PRODUCTS_SORT_EXPENSIVE",
  PRODUCTS_SORT_CHEAP: "PRODUCTS_SORT_CHEAP",
  PRODUCTS_SORT_ALPHABETICALLY: "PRODUCTS_SORT_ALPHABETICALLY",
  PRODUCT_CREATE: "PRODUCT_CREATE",
};
